/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("web.perf.kotlin-application-conventions")
    kotlin("plugin.serialization").version("1.7.21")
}

val vertxVersion = "4.3.6"

dependencies {
    implementation(platform("io.vertx:vertx-stack-depchain:$vertxVersion"))
    implementation("io.vertx:vertx-web")
    implementation("io.vertx:vertx-lang-kotlin")
    implementation("io.vertx:vertx-lang-kotlin-coroutines")
    implementation("io.netty:netty-transport-native-epoll:4.1.85.Final")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")

    implementation("org.slf4j:slf4j-api:1.7.+")
    implementation("ch.qos.logback:logback-classic:1.2.+")
}

application {
    // Define the main class for the application.
    mainClass.set("web.perf.app-vertx.AppKt")
}
