/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package web.perf.app.vertx.kotlinx

import io.vertx.core.DeploymentOptions
import io.vertx.core.Vertx
import io.vertx.ext.web.Router
import io.vertx.ext.web.handler.BodyHandler
import io.vertx.ext.web.handler.TimeoutHandler
import io.vertx.kotlin.coroutines.CoroutineVerticle
import io.vertx.kotlin.coroutines.await
import io.vertx.kotlin.coroutines.dispatcher
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import web.perf.app.vertx.app.model.SimpleModel
import java.time.Instant


fun main() {
    val vertx = Vertx.vertx()
    GlobalScope.launch(vertx.dispatcher()) {
        vertx.deployVerticle(WebVerticle::class.java, DeploymentOptions().setInstances(7))
    }
}

class WebVerticle : CoroutineVerticle() {
    override suspend fun start() {
        val http = vertx.createHttpServer()
        val router = Router.router(vertx)
        router.route().handler(BodyHandler.create())
        router.route().handler(TimeoutHandler.create(5000))
        router.get("/api/v1/test").coroutineHandler {
            it.end(Json.encodeToString(SimpleModel("test", Instant.now())))
        }
        http.requestHandler(router)
        http.listen(8080).await()
    }
}
