/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
//    kotlin ("jvm") version "1.7.21"
//    application
    id("web.perf.kotlin-application-conventions")
    kotlin("plugin.serialization").version("1.7.21")
}

val ktorVersion = "2.2.1"

application {
    mainClass.set("web.perf.app.ktor.App")
}

dependencies {
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("io.ktor:ktor-server-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
    implementation("ch.qos.logback:logback-classic:1.2.+")
}

application {
    // Define the main class for the application.
    mainClass.set("web.perf.app-vertx.AppKt")
}
