/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("web.perf.kotlin-application-conventions")
}

val vertxVersion = "4.3.6"

dependencies {
    implementation(platform("io.vertx:vertx-stack-depchain:$vertxVersion"))
    implementation("io.vertx:vertx-web")
    implementation("io.vertx:vertx-lang-kotlin")
    implementation("io.vertx:vertx-lang-kotlin-coroutines")
    implementation("io.netty:netty-transport-native-epoll:4.1.85.Final")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.+")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.+")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.9.2")

    implementation("org.slf4j:slf4j-api:1.7.+")
    implementation("ch.qos.logback:logback-classic:1.2.+")
}

application {
    // Define the main class for the application.
    mainClass.set("web.perf.app-vertx.AppKt")
}
